### ISSUE TITLE
Post -Track II training Ideas collections!

### ISSUE THREAD

**Issue by maliarich** [ASKnet-Open-Training/Minimal-Repair-Setup#11]

**Comment by timmwille** [comment]
what Ideas are we talking about @maliarich or can we move this somewhere else? to the Track II Repo or in the general https://github.com/ASKnet-Open-Training/CommunityRepairCafe Repo if primarily related to repairs?

**Comment by maliarich** [comment]
I meant  ...what next after the track II. Could be repairs etc. And binds the team(s) together.

**Comment by timmwille** [comment]
> I meant ...what next after the track II. Could be repairs etc. And binds the team(s) together.

good catch, though I think we might discuss this somewhere else (I have a few Ideas like the Discussions section or other Repo) not in the technical setup area? feel free to move/open this issue somewhere else or close this one after.. :+1:
